from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('',
         views.index,
         name='index'),
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_list'),
    path('create/',
         views.make_post,
         name='post_create'),
    path('profile/<str:username>/',
         views.profile,
         name='profile'),
    path('post/<int:post_id>/',
         views.post_page,
         name='post_detail'),
    path('favourite/',
         views.favourite,
         name='favourite'),
    path('post/<int:post_id>/comments/',
         views.comment_create,
         name='comment_create'),
    path('post/<int:comment_id>/comment/delete/',
         views.delete_comment,
         name='delete_comment'),
    path('profile/<str:username>/follow',
         views.subscribe,
         name='follow'),
    path('profile/<str:username>/unfollow',
         views.unsubscribe,
         name='unfollow'),
    path('post/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    path('post/<int:post_id>/delete/',
         views.delete_post,
         name='delete_post'),
    path('profile/<str:username>/edit',
         views.edit_profile,
         name='edit_profile'),
]
