# Generated by Django 2.2.16 on 2025-08-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20250807_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.TextField(blank=True, default='No name', max_length=32, verbose_name='Ник пользователя'),
        ),
    ]
